export interface InstagramCampaignAsset {
  id: string;
  index: number;
  url: string;
  shortcode: string;
  theme: 'TEASER' | 'HERITAGE' | 'FILM' | 'ARCH';
  headline: string;
  subheadline: string;
  likes: string;
  likesCount: number;
  comments: string;
  commentsCount: number;
  views: string;
  viewsCount: number;
  postDate: string;
  captionSnippet: string;
  localImage: string;
}

export const KRISALA_CAMPAIGN_ASSETS: InstagramCampaignAsset[] = [
  {
    id: 'asset-01',
    index: 1,
    url: 'https://www.instagram.com/p/DKt9-4ZIJ7a/',
    shortcode: 'DKt9-4ZIJ7a',
    theme: 'TEASER',
    headline: 'This Isn’t Hype. This Is Heritage.',
    subheadline: 'Teaser film revealing neoclassical colonnades and the beginning of Pune’s township revolution.',
    likes: '145',
    likesCount: 145,
    comments: '20',
    commentsCount: 20,
    views: '8.4K',
    viewsCount: 8400,
    postDate: 'June 10, 2025',
    captionSnippet: 'This isn’t hype. This is heritage. The wait is over, the revolution begins. Neoclassical towers rising in North Hinjawadi.',
    localImage: '/projects/krisala-hiranandani/ig_asset_01.jpg',
  },
  {
    id: 'asset-02',
    index: 2,
    url: 'https://www.instagram.com/p/DKzL8KLowKH/',
    shortcode: 'DKzL8KLowKH',
    theme: 'HERITAGE',
    headline: '105-Acre Integrated Township Inception',
    subheadline: 'Blessings at Shreemant Dagdusheth Halwai Ganpati Mandir and the formal launch announcement.',
    likes: '111',
    likesCount: 111,
    comments: '4',
    commentsCount: 4,
    views: '6.2K',
    viewsCount: 6200,
    postDate: 'June 12, 2025',
    captionSnippet: 'On February 20, 2025, the journey began. Hiranandani Communities and Krisala Developers launch a 105-acre township in North Hinjawadi.',
    localImage: '/projects/krisala-hiranandani/ig_asset_02.jpg',
  },
  {
    id: 'asset-03',
    index: 3,
    url: 'https://www.instagram.com/p/DK4PUPeoS0c/',
    shortcode: 'DK4PUPeoS0c',
    theme: 'HERITAGE',
    headline: 'The Headlines Said It All',
    subheadline: 'Full-page regional announcements capturing the arrival of a legacy in the making.',
    likes: '40',
    likesCount: 40,
    comments: '2',
    commentsCount: 2,
    views: '3.8K',
    viewsCount: 3800,
    postDate: 'June 14, 2025',
    captionSnippet: 'Krisala × Hiranandani wasn’t just announced, it was welcomed with full-page stories. Pune witnessed the arrival of a legacy.',
    localImage: '/projects/krisala-hiranandani/ig_asset_03.jpg',
  },
  {
    id: 'asset-04',
    index: 4,
    url: 'https://www.instagram.com/p/DK9WiM-PJBd/',
    shortcode: 'DK9WiM-PJBd',
    theme: 'TEASER',
    headline: 'History Always Has Two Sides',
    subheadline: 'Those who believed, and those who wished they had. Hinjawadi’s generational turning point.',
    likes: '46',
    likesCount: 46,
    comments: '0',
    commentsCount: 0,
    views: '4.1K',
    viewsCount: 4100,
    postDate: 'June 16, 2025',
    captionSnippet: 'History is calling once again, and now, it’s Hinjawadi’s time. Will you watch it happen or claim your place in it?',
    localImage: '/projects/krisala-hiranandani/ig_asset_04.jpg',
  },
  {
    id: 'asset-05',
    index: 5,
    url: 'https://www.instagram.com/p/DLFThC3ImjY/',
    shortcode: 'DLFThC3ImjY',
    theme: 'HERITAGE',
    headline: 'The Name That Brought A Legacy Home',
    subheadline: 'Parchment editorial layout celebrating Krisala’s tribute to the city of Pune.',
    likes: '62',
    likesCount: 62,
    comments: '1',
    commentsCount: 1,
    views: '5.3K',
    viewsCount: 5300,
    postDate: 'June 19, 2025',
    captionSnippet: 'This township is more than a collaboration. It’s Krisala’s tribute to Pune. Alongside Hiranandani, the legacy evolves.',
    localImage: '/projects/krisala-hiranandani/ig_asset_05.jpg',
  },
  {
    id: 'asset-06',
    index: 6,
    url: 'https://www.instagram.com/p/DLPR0dUP-rk/',
    shortcode: 'DLPR0dUP-rk',
    theme: 'HERITAGE',
    headline: 'When Vision Turns Into Reality',
    subheadline: 'Chronological timeline tracing 1991 Powai, 2000 Thane, and the 2025 Pune frontier.',
    likes: '33',
    likesCount: 33,
    comments: '0',
    commentsCount: 0,
    views: '3.5K',
    viewsCount: 3500,
    postDate: 'June 23, 2025',
    captionSnippet: '1991 Powai? Wilderness. 2000 Thane? A gamble. Now it’s your turn, your time, and your township. Which side are you on?',
    localImage: '/projects/krisala-hiranandani/ig_asset_06.jpg',
  },
  {
    id: 'asset-07',
    index: 7,
    url: 'https://www.instagram.com/p/DMVGVSkITVZ/',
    shortcode: 'DMVGVSkITVZ',
    theme: 'ARCH',
    headline: 'The Golden Line To North Hinjawadi',
    subheadline: 'Architectural line-art wireframe illustrating Mumbai’s skyline extending into Pune.',
    likes: '165',
    likesCount: 165,
    comments: '0',
    commentsCount: 0,
    views: '9.8K',
    viewsCount: 9800,
    postDate: 'July 20, 2025',
    captionSnippet: 'The golden line etched into Mumbai’s skyline now leads to North Hinjawadi, Pune. History, rewriting itself.',
    localImage: '/projects/krisala-hiranandani/ig_asset_07.jpg',
  },
  {
    id: 'asset-08',
    index: 8,
    url: 'https://www.instagram.com/p/DMXrHPuPn17/',
    shortcode: 'DMXrHPuPn17',
    theme: 'ARCH',
    headline: 'From Powai’s Soul to Pune’s Culture',
    subheadline: 'Vector elevation graphics pairing neoclassical architecture with Pune’s cultural fabric.',
    likes: '177',
    likesCount: 177,
    comments: '2',
    commentsCount: 2,
    views: '11.2K',
    viewsCount: 11200,
    postDate: 'July 21, 2025',
    captionSnippet: 'From the soul of Powai, to the culture of Pune. Krisala brings Hiranandani’s excellence to the skyline.',
    localImage: '/projects/krisala-hiranandani/ig_asset_08.jpg',
  },
  {
    id: 'asset-09',
    index: 9,
    url: 'https://www.instagram.com/p/DMsRePiPI7B/',
    shortcode: 'DMsRePiPI7B',
    theme: 'FILM',
    headline: 'When Legendary Minds Meet',
    subheadline: 'Teaser for the vision film hearing directly from India’s foremost real estate pioneers.',
    likes: '138',
    likesCount: 138,
    comments: '0',
    commentsCount: 0,
    views: '8.9K',
    viewsCount: 8900,
    postDate: 'July 29, 2025',
    captionSnippet: 'What happens when India’s most legendary minds meet? Hear the dream behind India’s biggest opportunity.',
    localImage: '/projects/krisala-hiranandani/ig_asset_09.jpg',
  },
  {
    id: 'asset-10',
    index: 10,
    url: 'https://www.instagram.com/p/DMu2ORFoJD3/',
    shortcode: 'DMu2ORFoJD3',
    theme: 'FILM',
    headline: 'Legacy of Excellence & Biophilic Hills',
    subheadline: 'Kinetic screen typography tracked across the Sahyadri mountain slopes in North Hinjawadi.',
    likes: '157',
    likesCount: 157,
    comments: '1',
    commentsCount: 1,
    views: '10.4K',
    viewsCount: 10400,
    postDate: 'July 30, 2025',
    captionSnippet: 'Powai wasn’t built in a day. Today that same vision looks west to North Hinjawadi. Legacy of excellence meets green luxury.',
    localImage: '/projects/krisala-hiranandani/ig_asset_10.jpg',
  },
  {
    id: 'asset-11',
    index: 11,
    url: 'https://www.instagram.com/p/DN5RXYxDkrm/',
    shortcode: 'DN5RXYxDkrm',
    theme: 'FILM',
    headline: 'Ideas In White — The Vision Film Launch',
    subheadline: 'The landmark vision film featuring Dr. Niranjan Hiranandani and the full Krisala leadership council.',
    likes: '160',
    likesCount: 160,
    comments: '0',
    commentsCount: 0,
    views: '12.5K',
    viewsCount: 12500,
    postDate: 'August 28, 2025',
    captionSnippet: 'Krisala x Hiranandani presents Ideas In White! A rare film capturing the visionaries behind the World’s First Resort-Style Development.',
    localImage: '/projects/krisala-hiranandani/ig_asset_11.jpg',
  },
];

export interface MotionKeyframe {
  id: string;
  number: string;
  title: string;
  subtitle: string;
  image: string;
}

export const KRISALA_KEYFRAMES: MotionKeyframe[] = [
  {
    id: 'frame-01',
    number: '01',
    title: 'Ideas In White — Title Sequence',
    subtitle: 'Widescreen identity mark on pure white architectural canvas',
    image: '/projects/krisala-hiranandani/youtube_hero_poster.jpg',
  },
  {
    id: 'frame-02',
    number: '02',
    title: 'Neoclassical Wireframe Overlays',
    subtitle: 'Fine-line vector elevations tracing classical pediments and colonnades',
    image: '/projects/krisala-hiranandani/ig_asset_08.jpg',
  },
  {
    id: 'frame-03',
    number: '03',
    title: 'Spatial Landscape Typography',
    subtitle: 'Kinetic screen typography tracked across Sahyadri hill slopes',
    image: '/projects/krisala-hiranandani/ig_asset_10.jpg',
  },
  {
    id: 'frame-04',
    number: '04',
    title: 'Leadership Keynote Framing',
    subtitle: 'Minimalist architectural framing for visionary keynote dialogue',
    image: '/projects/krisala-hiranandani/ig_asset_11.jpg',
  },
];

export const KRISALA_METRICS_SUMMARY = {
  totalAssets: 11,
  totalLikes: 1088,
  totalComments: 30,
  totalEstimatedViews: '1,00,000+',
  acreage: '105+ Acres',
  location: 'North Hinjawadi, Pune',
  studioCredit: 'Bandish Studios',
};
