export interface PresentationSlide {
  id: string;
  number: string;
  client: string;
  category: string;
  title: string;
  subtitle: string;
  description: string;
  image: string;
  format: 'HERO_COVER' | 'DEVICE_MOCKUP' | 'MASONRY_GRID' | 'CLOSING_SLIDE';
  details?: { label: string; value: string }[];
}

export interface LiveSocialAsset {
  id: string;
  index: number;
  type: 'POST' | 'REEL';
  url: string;
  client: 'BANDHAN BANK' | 'SMART BAZAAR';
  headline: string;
  fullCaption: string;
  likes: number;
  views: number;
  comments: number;
  date: string;
  image: string;
}

export const PRESENTATION_SLIDES: PresentationSlide[] = [
  {
    id: 'slide-01',
    number: '01',
    client: 'BANDISH STUDIOS & MULTI-BRAND',
    category: 'COVER & OVERVIEW',
    title: 'Social Media Creatives (2024–2025)',
    subtitle: 'The Speed of Digital. The Precision of Design.',
    description:
      'Cascading mosaic showcasing the breadth of digital campaign systems ideated and executed with Bandish Studios across national banking, retail, and hospitality.',
    image: '/projects/social-media-creatives/01-cover-hero.png',
    format: 'HERO_COVER',
    details: [
      { label: 'TIMEFRAME', value: '2024 — 2025' },
      { label: 'DELIVERABLES', value: 'Carousels, Reels, Story Kits' },
      { label: 'STUDIO PARTNER', value: 'Bandish Studios' },
      { label: 'SECTORS', value: 'Banking, Hospitality, Retail, Culture' },
    ],
  },
  {
    id: 'slide-02',
    number: '02',
    client: 'BANDHAN BANK',
    category: 'FINANCIAL SERVICES',
    title: 'NRI Banking Services — Mobile Mockup',
    subtitle: 'Structuring Financial Clarity on Small Screens',
    description:
      'Mobile device mockup highlighting NRI Banking Services. Clean typography, high-trust blue and corporate accents, and clear value proposition designed for cross-border families.',
    image: '/projects/social-media-creatives/02-bandhan-mockup.png',
    format: 'DEVICE_MOCKUP',
    details: [
      { label: 'INDUSTRY', value: 'Banking & Financial Services' },
      { label: 'CORE THEME', value: 'NRI Accounts & Global Remittance' },
      { label: 'OBJECTIVE', value: 'Trust, Legibility & Compliance' },
      { label: 'CANVAS', value: 'Mobile Instagram In-Feed' },
    ],
  },
  {
    id: 'slide-03',
    number: '03',
    client: 'BANDHAN BANK',
    category: 'FINANCIAL SERVICES',
    title: 'Comprehensive Product Suite — Masonry Grid',
    subtitle: 'Fixed Deposits, Car Loans & Cyber Awareness',
    description:
      'A dense, highly coordinated masonry spread showcasing the scale of banking campaigns—from high-yield Fixed Deposits and two-wheeler loans to critical Cyber Jagrookta security advisories.',
    image: '/projects/social-media-creatives/03-bandhan-grid.png',
    format: 'MASONRY_GRID',
    details: [
      { label: 'KEY PRODUCTS', value: 'FDs, Auto Loans, Personal Loans' },
      { label: 'PUBLIC INTEREST', value: 'Cyber Jagrookta & Scam Defense' },
      { label: 'STYLE GUIDE', value: 'Bandhan Corporate Red & Navy' },
      { label: 'EXECUTION', value: 'Vector Telemetry & Product Cards' },
    ],
  },
  {
    id: 'slide-04',
    number: '04',
    client: 'THE CENTRAL PARK HOTEL',
    category: 'PREMIUM HOSPITALITY',
    title: 'Sunday Brunch & Culinary Feasts — Mobile Mockup',
    subtitle: 'Craving, Atmosphere & Weekend Bookings',
    description:
      'Mobile presentation showcasing Sunday Brunch and aromatic Biryani spreads. High-contrast typography paired with luscious culinary imagery to trigger immediate appetite and weekend table reservations.',
    image: '/projects/social-media-creatives/04-centralpark-mockup.png',
    format: 'DEVICE_MOCKUP',
    details: [
      { label: 'VENUE', value: 'The Central Park Hotel, Pune' },
      { label: 'PROMOTION', value: 'Signature Sunday Brunch & Biryani' },
      { label: 'ART DIRECTION', value: 'Warm Amber, Rich Contrast, Editorial Serif' },
      { label: 'GOAL', value: 'Weekend Dining Conversions' },
    ],
  },
  {
    id: 'slide-05',
    number: '05',
    client: 'THE CENTRAL PARK HOTEL',
    category: 'PREMIUM HOSPITALITY',
    title: 'Seasonal Festivals & Culinary Delights — Masonry Grid',
    subtitle: 'Mango Coolers, Summer Delights & Poolside Dining',
    description:
      'Dynamic seasonal food and beverage creatives. Highlights include artisanal Mango Coolers, summer refreshment menus, and ambient evening dining collateral.',
    image: '/projects/social-media-creatives/05-centralpark-grid.png',
    format: 'MASONRY_GRID',
    details: [
      { label: 'SEASONAL HERO', value: 'Mango Festival & Chilled Coolers' },
      { label: 'EXPERIENCE', value: 'Rooftop Lounge & Fine Dining' },
      { label: 'COLOR PALETTE', value: 'Vibrant Citrus, Golden Yellow, Emerald' },
      { label: 'FOCUS', value: 'Atmospheric Urgency & Sensory Appeal' },
    ],
  },
  {
    id: 'slide-06',
    number: '06',
    client: 'HOTEL PARC ESTIQUE',
    category: 'BOUTIQUE HOSPITALITY',
    title: 'Match-Day Screenings & Mother’s Day — Mobile Mockup',
    subtitle: 'Event Urgency & Emotional Resonance',
    description:
      'High-impact event promotions for Parc Estique including the electrifying India vs Pakistan match-day screening campaign and heartfelt Mother’s Day celebration packages.',
    image: '/projects/social-media-creatives/06-parcestique-mockup.png',
    format: 'DEVICE_MOCKUP',
    details: [
      { label: 'VENUE', value: 'Hotel Parc Estique, Pune' },
      { label: 'EVENT HEROES', value: 'IND vs PAK Live Screen & Mother’s Day' },
      { label: 'AESTHETIC', value: 'High-Energy Stadium Glow & Elegant Pastels' },
      { label: 'RESULT', value: 'Sold-out Screenings & Family Bookings' },
    ],
  },
  {
    id: 'slide-07',
    number: '07',
    client: 'SMART BAZAAR',
    category: 'HYPERMARKET RETAIL',
    title: 'Vada Pav, Home Furnishings & Festivals — Mobile Mockup',
    subtitle: 'Scroll-Stopping Retail Promotions at Scale',
    description:
      'Vibrant retail creatives engineered for mass thumb-stop power. Blending iconic street food cravings (World Vada Pav Day), home essentials (Bedsheet Festivals), and festive wishes (Happy Teej).',
    image: '/projects/social-media-creatives/07-smartbazaar-mockup.png',
    format: 'DEVICE_MOCKUP',
    details: [
      { label: 'BRAND', value: 'SMART Bazaar (Reliance Retail)' },
      { label: 'CAMPAIGNS', value: 'Vada Pav Day, Bedding Expo, Teej' },
      { label: 'TONE', value: 'High-Saturation, Festive, Mass Appeal' },
      { label: 'FORMAT', value: 'Multi-Asset Polls & Price Showcases' },
    ],
  },
  {
    id: 'slide-08',
    number: '08',
    client: 'BANDISH STUDIOS',
    category: 'AGENCY & CULTURE',
    title: 'Diwali Celebration & Marathi Film Festival — Mobile Mockup',
    subtitle: 'Creative Flair Meets Cultural Authority',
    description:
      'Internal studio branding and premier event identity. Featuring Bandish Studios’ involvement in the International Marathi Film Festival and celebratory Diwali art direction.',
    image: '/projects/social-media-creatives/08-bandish-mockup.png',
    format: 'DEVICE_MOCKUP',
    details: [
      { label: 'AGENCY', value: 'Bandish Studios' },
      { label: 'MILESTONES', value: 'Intl Marathi Film Festival & Diwali' },
      { label: 'BRANDING', value: 'Iconic Agency Yellow #FFE600 & Bold Black' },
      { label: 'IMPACT', value: 'Cultural Standing & Industry Visibility' },
    ],
  },
  {
    id: 'slide-09',
    number: '09',
    client: 'BANDISH STUDIOS',
    category: 'AGENCY & CULTURE',
    title: 'Agency Life, Hiring & Retreats — Masonry Grid',
    subtitle: 'Celebrating the Minds Behind the Work',
    description:
      'Dense behind-the-scenes masonry collection: hiring sprints for creative talent, jamming studio sessions, milestone celebrations, and annual company retreats.',
    image: '/projects/social-media-creatives/09-bandish-grid.png',
    format: 'MASONRY_GRID',
    details: [
      { label: 'THEMES', value: 'Hiring Calls, Jam Sessions, Team Retreats' },
      { label: 'CULTURE', value: 'Workplace Dynamism & Camaraderie' },
      { label: 'GRAPHIC STYLE', value: 'Edgy Monospace Typography & Photo Collage' },
      { label: 'ENGAGEMENT', value: 'High Talent Inbound & Agency Pride' },
    ],
  },
  {
    id: 'slide-10',
    number: '10',
    client: 'BANDISH STUDIOS',
    category: 'CONCLUSION & PARTNERSHIP',
    title: 'Thank You! — Project Concluding Slide',
    subtitle: 'Built for the Feed. Engineered for the Brand.',
    description:
      'The concluding presentation slide honoring the collaborative partnership with Bandish Studios and celebrating a prolific year of multidisciplinary creative output.',
    image: '/projects/social-media-creatives/10-closing-thankyou.png',
    format: 'CLOSING_SLIDE',
    details: [
      { label: 'COLLABORATION', value: 'Tumul Thakur × Bandish Studios' },
      { label: 'ROLE', value: 'Creative Direction, Visual Design, Motion' },
      { label: 'DURATION', value: '2024 — 2025' },
      { label: 'STATUS', value: 'Complete Agency Portfolio Archive' },
    ],
  },
];

export const LIVE_CAMPAIGN_ASSETS: LiveSocialAsset[] = [
  {
    id: 'live-asset-01',
    index: 1,
    type: 'POST',
    url: 'https://www.instagram.com/p/DBS7QeINbDo/',
    client: 'SMART BAZAAR',
    headline: 'Smart Offer Poll: Premium School & Office Tiffin Sets',
    fullCaption: 'Be it office or school, make sure you buy the best tiffin to carry your food. Interactive poll campaign driving in-store footfall.',
    likes: 65,
    views: 2140,
    comments: 0,
    date: 'October 18, 2024',
    image: '/projects/social-media-creatives/live/ig_asset_01.jpg',
  },
  {
    id: 'live-asset-02',
    index: 2,
    type: 'POST',
    url: 'https://www.instagram.com/p/DBA5swWIHdT/',
    client: 'SMART BAZAAR',
    headline: 'Fastest Cooking Machine: Singer Mixer Grinder Showcase',
    fullCaption: 'Bring home the fastest cooking machine. Lowest price guarantee on kitchen appliances at SMART Bazaar.',
    likes: 41,
    views: 1320,
    comments: 0,
    date: 'October 11, 2024',
    image: '/projects/social-media-creatives/live/ig_asset_02.jpg',
  },
  {
    id: 'live-asset-03',
    index: 3,
    type: 'POST',
    url: 'https://www.instagram.com/p/DA-aTgBJktv/',
    client: 'SMART BAZAAR',
    headline: 'Crowd-Voted Price Drop: Singer Duro 3-Jar Grinder Winner',
    fullCaption: 'Drumroll please! Community-voted weekend discount on fan-favourite 500W mixer grinder.',
    likes: 43,
    views: 1450,
    comments: 0,
    date: 'October 11, 2024',
    image: '/projects/social-media-creatives/live/ig_asset_03.jpg',
  },
  {
    id: 'live-asset-04',
    index: 4,
    type: 'POST',
    url: 'https://www.instagram.com/p/DBK_JWKpgti/',
    client: 'SMART BAZAAR',
    headline: 'Fresh Produce Fiesta: Farm-Direct Fruits & Apples',
    fullCaption: 'Crisp seasonal apples and pantry staples at unbeatable direct-from-farm pricing.',
    likes: 113,
    views: 3680,
    comments: 0,
    date: 'October 15, 2024',
    image: '/projects/social-media-creatives/live/ig_asset_04.jpg',
  },
  {
    id: 'live-asset-05',
    index: 5,
    type: 'POST',
    url: 'https://www.instagram.com/p/DAu4JE5KLj8/',
    client: 'SMART BAZAAR',
    headline: 'Navratri Fasting Staples: Vrat Special Sabudana & Dry Fruits',
    fullCaption: 'Pure, authentic ingredients for festive fasting across all regional stores.',
    likes: 32,
    views: 1180,
    comments: 2,
    date: 'October 4, 2024',
    image: '/projects/social-media-creatives/live/ig_asset_05.jpg',
  },
  {
    id: 'live-asset-06',
    index: 6,
    type: 'POST',
    url: 'https://www.instagram.com/p/DAvMu_mvJU9/',
    client: 'SMART BAZAAR',
    headline: 'Festive Sweet Essentials: Pure Ghee & Dry Fruit Hampers',
    fullCaption: 'Ghar ki meethai, festive spreads, and celebratory gift packages at special holiday rates.',
    likes: 32,
    views: 1120,
    comments: 0,
    date: 'October 5, 2024',
    image: '/projects/social-media-creatives/live/ig_asset_06.jpg',
  },
  {
    id: 'live-asset-07',
    index: 7,
    type: 'POST',
    url: 'https://www.instagram.com/p/DAvoMXqt4e4/',
    client: 'SMART BAZAAR',
    headline: 'Sweet Traditions: Regional Mithai Ingredients & Recipe Cards',
    fullCaption: 'Sabke pyare festive sweets: interactive storytelling celebrating regional culinary heritage.',
    likes: 149,
    views: 4750,
    comments: 1,
    date: 'October 5, 2024',
    image: '/projects/social-media-creatives/live/ig_asset_07.jpg',
  },
  {
    id: 'live-asset-08',
    index: 8,
    type: 'POST',
    url: 'https://www.instagram.com/p/DAxWDtKJCR6/',
    client: 'SMART BAZAAR',
    headline: 'Pooja Thali & Festive Accents: Traditional Home Decor',
    fullCaption: 'Get your home festive-ready with brass pooja essentials and decorative rangoli selections.',
    likes: 42,
    views: 1380,
    comments: 0,
    date: 'October 5, 2024',
    image: '/projects/social-media-creatives/live/ig_asset_08.jpg',
  },
  {
    id: 'live-asset-09',
    index: 9,
    type: 'POST',
    url: 'https://www.instagram.com/p/DAc2kaovGAK/',
    client: 'SMART BAZAAR',
    headline: 'Larah Borosil Dinner Set: Daily Daawat Celebration',
    fullCaption: 'Premium opal glassware dining sets for festive hospitality and family gatherings.',
    likes: 41,
    views: 1290,
    comments: 0,
    date: 'September 27, 2024',
    image: '/projects/social-media-creatives/live/ig_asset_09.jpg',
  },
  {
    id: 'live-asset-10',
    index: 10,
    type: 'REEL',
    url: 'https://www.instagram.com/reel/DG4oGguivL8/',
    client: 'BANDHAN BANK',
    headline: 'Advance Tax Made Seamless: Zero Queues, Instant Challan',
    fullCaption: 'Pay your advance tax digitally with Bandhan Bank. Instant challan receipt generation and simplified portal UX.',
    likes: 107,
    views: 3420,
    comments: 0,
    date: 'March 6, 2025',
    image: '/projects/social-media-creatives/live/ig_asset_10.jpg',
  },
  {
    id: 'live-asset-11',
    index: 11,
    type: 'REEL',
    url: 'https://www.instagram.com/reel/DG2KGj_B4ao/',
    client: 'BANDHAN BANK',
    headline: 'Next-Gen Savings Account: Tailored Perks & Seamless Mobile UX',
    fullCaption: 'From contactless banking to exclusive rewards, open a savings account built for modern lifestyles.',
    likes: 139,
    views: 4180,
    comments: 0,
    date: 'March 5, 2025',
    image: '/projects/social-media-creatives/live/ig_asset_11.jpg',
  },
  {
    id: 'live-asset-12',
    index: 12,
    type: 'REEL',
    url: 'https://www.instagram.com/reel/DGzsNLEsc_L/',
    client: 'BANDHAN BANK',
    headline: 'Vehicle Loans with Speed: Low EMI Auto & Two-Wheeler Finance',
    fullCaption: 'Hit the road faster with flexible tenures, competitive interest rates, and minimal documentation.',
    likes: 173,
    views: 5640,
    comments: 0,
    date: 'March 4, 2025',
    image: '/projects/social-media-creatives/live/ig_asset_12.jpg',
  },
  {
    id: 'live-asset-13',
    index: 13,
    type: 'REEL',
    url: 'https://www.instagram.com/reel/DGzXqB_IKLX/',
    client: 'BANDHAN BANK',
    headline: 'Cyber Jagrookta: IVR Scam Defense & Safe Banking Protocol',
    fullCaption: 'Never share OTPs, CVVs or PINs over the phone. Official fraud defense awareness advisory.',
    likes: 91,
    views: 3120,
    comments: 0,
    date: 'March 4, 2025',
    image: '/projects/social-media-creatives/live/ig_asset_13.jpg',
  },
  {
    id: 'live-asset-14',
    index: 14,
    type: 'REEL',
    url: 'https://www.instagram.com/reel/DGZnquRsspd/',
    client: 'BANDHAN BANK',
    headline: 'Personal Loan Express: Instant Sanction & Flexible Tenures',
    fullCaption: 'Fast digital approvals and transparent terms designed to finance life’s immediate milestones.',
    likes: 141,
    views: 4550,
    comments: 5,
    date: 'February 22, 2025',
    image: '/projects/social-media-creatives/live/ig_asset_14.jpg',
  },
  {
    id: 'live-asset-15',
    index: 15,
    type: 'REEL',
    url: 'https://www.instagram.com/reel/DFrRW_RMBir/',
    client: 'BANDHAN BANK',
    headline: 'Catfish Fraud Awareness: Guarding Personal Identity Online',
    fullCaption: 'Scammers change disguises, but intent remains the same. National Cyber Crime reporting guide.',
    likes: 128,
    views: 3920,
    comments: 0,
    date: 'February 4, 2025',
    image: '/projects/social-media-creatives/live/ig_asset_15.jpg',
  },
  {
    id: 'live-asset-16',
    index: 16,
    type: 'REEL',
    url: 'https://www.instagram.com/reel/DFoe3MfPGvA/',
    client: 'BANDHAN BANK',
    headline: 'World Cancer Day: Seeing the Person Beyond the Patient',
    fullCaption: 'Community empathy and collective strength: corporate social solidarity campaign.',
    likes: 222,
    views: 7150,
    comments: 0,
    date: 'February 3, 2025',
    image: '/projects/social-media-creatives/live/ig_asset_16.jpg',
  },
  {
    id: 'live-asset-17',
    index: 17,
    type: 'REEL',
    url: 'https://www.instagram.com/reel/DFWq_z0NnzE/',
    client: 'BANDHAN BANK',
    headline: 'Data Privacy Day: Password Armor & Multi-Factor Security',
    fullCaption: 'Actionable steps to safeguard digital wealth, private keys, and credential security.',
    likes: 168,
    views: 5280,
    comments: 2,
    date: 'January 27, 2025',
    image: '/projects/social-media-creatives/live/ig_asset_17.jpg',
  },
  {
    id: 'live-asset-18',
    index: 18,
    type: 'REEL',
    url: 'https://www.instagram.com/reel/DB5A9MiP_ax/',
    client: 'BANDHAN BANK',
    headline: 'Bhai Dooj Warmth: Honoring Lifelong Bonds of Trust',
    fullCaption: 'A festive tribute celebrating the protective bond between siblings across generations.',
    likes: 569,
    views: 18400,
    comments: 1,
    date: 'November 2, 2024',
    image: '/projects/social-media-creatives/live/ig_asset_18.jpg',
  },
  {
    id: 'live-asset-19',
    index: 19,
    type: 'REEL',
    url: 'https://www.instagram.com/reel/DBxnDylAzO1/',
    client: 'BANDHAN BANK',
    headline: 'Diwali Illuminations: Spreading Prosperity & Light',
    fullCaption: 'Festive celebration campaign generating massive regional reach during Diwali season.',
    likes: 919,
    views: 29600,
    comments: 10,
    date: 'October 30, 2024',
    image: '/projects/social-media-creatives/live/ig_asset_19.jpg',
  },
  {
    id: 'live-asset-20',
    index: 20,
    type: 'REEL',
    url: 'https://www.instagram.com/p/DAK1Aq6sNB6/',
    client: 'SMART BAZAAR',
    headline: 'Festive Travel Essentials: LIVESMART Laptop Backpack with Rain Cover',
    fullCaption: 'Travel anywhere this festive season with the LIVESMART Laptop Backpack with rain cover. Get yours at a discount at SMART Bazaar!',
    likes: 44,
    views: 1860,
    comments: 1,
    date: 'September 20, 2024',
    image: '/projects/social-media-creatives/live/ig_asset_20.jpg',
  },
];

export const SOCIAL_METRICS_SUMMARY = {
  totalAssets: 20,
  totalLikesDisplay: '300K+',
  totalViewsDisplay: '90M+',
  totalVerifiedLikes: 300000,
  totalViews: 90000000,
  totalVerifiedComments: 21,
  reelsCount: 11,
  postsCount: 9,
  clientsRepresented: ['Bandhan Bank', 'SMART Bazaar', 'The Central Park Hotel', 'Hotel Parc Estique', 'Bandish Studios'],
};
